// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mcmcCpp
NumericVector mcmcCpp(int length, int success, int trials);
RcppExport SEXP _MCMCHMSampler_mcmcCpp(SEXP lengthSEXP, SEXP successSEXP, SEXP trialsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type length(lengthSEXP);
    Rcpp::traits::input_parameter< int >::type success(successSEXP);
    Rcpp::traits::input_parameter< int >::type trials(trialsSEXP);
    rcpp_result_gen = Rcpp::wrap(mcmcCpp(length, success, trials));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MCMCHMSampler_mcmcCpp", (DL_FUNC) &_MCMCHMSampler_mcmcCpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_MCMCHMSampler(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
